server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: pspPaymentMethods
          uri: lb://PSP-SERVICE
          predicates:
            - Path=/api/psp/paymentMethods/{merchantId}
            - Method=GET
        - id: pspPaymentMethodsSubscribeUrl
          uri: lb://PSP-SERVICE
          predicates:
            - Path=/api/psp/paymentMethods/subscribeUrl
            - Method=POST
        - id: pspPaymentMethodsSubscribe
          uri: lb://PSP-SERVICE
          predicates:
            - Path=/api/psp/paymentMethods/changeSubscription
            - Method=POST