server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: https://localhost:9001/eureka

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: pspPaymentMethods
          uri: lb://PSP-SERVICE
          predicates:
            - Path=/api/psp/paymentMethods/{merchantId} #to get all subscribed payment
            - Method=GET
        - id: pspPaymentMethodsSubscribeUrl
          uri: lb://PSP-SERVICE
          predicates:
            - Path=/api/psp/paymentMethods/subscribeUrl #to get URL for all subscribed payment types
            - Method=POST
        - id: pspPaymentMethodsSubscribe
          uri: lb://PSP-SERVICE
          predicates:
            - Path=/api/psp/paymentMethods/changeSubscription #to change subscription
            - Method=POST
        - id: pspPaymentMethodsPayment
          uri: lb://PSP-SERVICE
          predicates:
            - Path=/api/psp/paymentMethods/paymentUrl #to get all merchant's payment types
            - Method=POST
        - id: pspPaymentMethodsPaymentUrl
          uri: lb://PSP-SERVICE
          predicates:
            - Path=/api/psp/paymentMethods/payment/{merchantId} #to get URL for all merchant's payment types
            - Method=GET
        - id: pspChoosepaymentMethod
          uri: lb://PSP-SERVICE
          predicates:
            - Path=/api/psp/paymentMethods/choosePaymentMethod #to change subscription
            - Method=POST
        - id: bankServicecheckTransaction
          uri: lb://BANK-SERVICE
          predicates:
            - Path=/bank-service/checkTransaction #check executed transaction from acquirer bank
            - Method=POST
        - id: qrServicecheckTransaction
          uri: lb://QR-SERVICE
          predicates:
            - Path=/qr-service/checkTransaction #check executed transaction from acquirer bank over qr code
            - Method=POST
        - id: payPalTransactionId
          uri: lb://PAYPAL-SERVICE
          predicates:
            - Path=/paypal-service/transactions/{transactionId} #get paypal transaction by id
            - Method=GET
        - id: payPalTransactionSuccessId
          uri: lb://PAYPAL-SERVICE
          predicates:
            - Path=/paypal-service/transactions/{transactionId}/success #change paypal transaction status to success
            - Method=PUT
        - id: payPalTransactionCancelId
          uri: lb://PAYPAL-SERVICE
          predicates:
            - Path=/paypal-service/transactions/{transactionId}/cancel #change paypal transaction status to canceled
            - Method=PUT
        - id: pspPaymentWage
          uri: lb://PSP-SERVICE
          predicates:
            - Path=/api/psp/paymentMethods/paymentWage #payment wage
            - Method=POST